language: julia
os:
  - linux
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
script: dash test.sh
after_success: julia --project=coverage/ coverage/submit.jl
jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      script: julia --project=docs/ docs/document.jl
      after_success: skip
