language: julia
os:
  - linux
julia:
  - 1.0
  - 1.2
  - nightly
matrix:
  allow_failures:
    - julia: 1.0
    - julia: nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia --project --code-coverage=tracefile-%p.info --code-coverage=user build_and_test.jl
after_success:
  - if [[ $TRAVIS_JULIA_VERSION = 1.2 ]] && [[ $TRAVIS_OS_NAME = linux ]]; then
      julia --project=coverage coverage/coverage.jl;
    fi
jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs docs/document.jl
      after_success: skip
